### ISSUE TITLE
some invalid paths not redirecting to homepage

### ISSUE THREAD

**Issue by midfords** [paymog/Lunchr#7]
multi level paths (such as /users/example/) are not redirecting to homepage. Instead they are displaying the index.jade file with no partial inserted.

'black magic' in routes/index.js is to blame. (line 10)

**Comment by kjrcda** [comment]
Seems to be going to /partials/:name - will see if /partials/\* will catch it

**Comment by kjrcda** [comment]
It seems now that the angular update has gone through, this is no longer a problem.
